# Generated by Django 4.2.1 on 2023-05-06 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TKTUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetail',
            name='Issue_Related_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TKTUsers.issue_category'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='ticket_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TKTUsers.agent'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='ticket_raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='ticket_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='ticket_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TKTUsers.ticket_status_choice'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='website_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TKTUsers.category'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='website_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='website_technology',
            field=models.ManyToManyField(blank=True, null=True, related_name='website_technology', to='TKTUsers.technology_stack'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='websitename',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='websiteurl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
