# Generated by Django 4.2.1 on 2023-05-05 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TKTUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_role',
            name='Agent_Role_created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent_role',
            name='Agent_Role_update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
