# Generated by Django 4.2.1 on 2023-05-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TKTUsers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='Agent_technology_expert',
        ),
    ]
