# Generated by Django 4.2.1 on 2023-05-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TKTUsers', '0003_remove_ticketdetail_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetail',
            name='ticket_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TKTUsers.agent'),
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='ticket_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TKTUsers.ticket_status_choice'),
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='website_technology',
            field=models.ManyToManyField(blank=True, null=True, related_name='website_technology', to='TKTUsers.technology_stack'),
        ),
    ]
