# Generated by Django 4.2.1 on 2023-05-05 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TKTUsers', '0003_ticket_status_choice_ticket_status_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='Category_update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='technology_stack',
            name='technology_stack_created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology_stack',
            name='technology_stack_update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
