# Generated by Django 4.2.1 on 2023-05-05 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TKTUsers', '0004_category_category_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket_status_choice',
            options={'verbose_name_plural': 'Ticket Status Choice'},
        ),
        migrations.AddField(
            model_name='issue_category',
            name='Issue_Category_created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue_category',
            name='Issue_Category_update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
