# Generated by Django 4.2.1 on 2023-05-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TKTUsers', '0007_ticketdetail_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetail',
            name='website_technology',
            field=models.ManyToManyField(blank=True, null=True, related_name='website_technology', to='TKTUsers.technology_stack'),
        ),
    ]
